### ISSUE TITLE
"Invalid address 0x335 is pointing to reserved memory."

### ISSUE THREAD

**Issue by conneath** [dangreene0/PF2-Tools#2]
![image](https://user-images.githubusercontent.com/29014194/203644512-28c8c936-35a4-4b7a-96c4-0e43c5283853.png)

**Comment by rawra89** [comment]
This is probably related to the crashing, hopefully the hotfix coming will address this.

**Comment by rawra89** [comment]
This is fixed following the hotfix bins, closing this thread.

**Comment by conneath** [comment]
Maybe fixed with https://github.com/Pre-Fortress-2/PF2-Tools/commit/99ba26ca44b9b73fa5a1b4a646a0311ba87b79cc

**Comment by conneath** [comment]
nevermind 💀

**Comment by zxz41** [comment]
Should be fixed in b60197d
